version: "3.4"
services:
  api:
    container_name: ChatGPT
    ports:
      - 3080:3080               # Change it to 9000:3080 to use nginx
    image: chatgpt                # Comment this & uncomment below to build from docker hub image
    build:                                   # ^------
      context: .                              # ^------
      target: node                             # ^------v
    restart: always
    user: "${UID}:${GID}"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=mongodb+srv://modb12:t1sjeM9gxrfsOwJT@cluster0.ftwrwgp.mongodb.net/?retryWrites=true
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_HTTP_ADDR=meilisearch:7700
    volumes:
      - /app/client/node_modules
      - ./api:/app/api
      - ./.env:/app/.env
      - ./.env.development:/app/.env.development
      - ./.env.production:/app/.env.production
      - /app/api/node_modules
      - ./images:/app/client/public/images
  volumes:
      - ./meili_data:/meili_data